config/routes.rb
Rails.application.routes.draw do
  get 'cart/cart'
  devise_for :restaurants, controllers: {
    registrations: 'restaurants/registrations',
    sessions: 'restaurants/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to: "pages#home"
  # root to: "pages#authentication"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "pages/auth", to: "pages#authentication", as: :auth
  # routes for pages
  resources :pages
  # Defined routes for the restaurants
  get 'restaurants/dashboard', to: 'restaurants/dashboard#dashboard'
  get 'restaurants/:id/notification', to: 'restaurants/dashboard#notification', as: :restaurant_notification
  get 'users/dashboard', to: 'users/dashboard#dashboard'
  get 'users/:id/notification', to: 'users/dashboard#notification', as: :user_notification

  resources :restaurants do
    resources :reviews
    # Nested routes - foods belonging to restaurant
    resources :foods, only: [:new, :create, :edit, :index, :show]
    resources :foods, only: [:new, :create, :index, :show] do
      member do
        patch :published, :unpublished
      end
    end

    # Nested routes - reviews belonging to restaurant
    resources :reviews, only: [:index, :create, :new]
    # Nested routes - orders related to a specific restaurant
    # resources :orders, only: [:index, :create, :new]
  end

  resources :foods do
    resources :order_lines, only: [:create]
    patch :published, on: :collection
  end

  resources :orders do
    member do
      patch 'checkout'
    end
    collection do
      get 'past'
    end
  end



  resources :foods, only: [:edit, :update, :destroy, :show]

  get '/search', to: 'search#list', as: :search
  get '/search/map', to: 'search#map', as: :search_map

  # routes related to orders and carts
  get '/cart', to: 'cart#cart', as: :cart
  get 'order_lines/:id' => "order_lines#show", as: "order_lines"

  get 'order_lines/:id/add' => "order_lines#add_quantity", as: "orders_lines_quantity"
  post 'order_lines/:id/add' => "order_lines#add_quantity", as: "order_lines_add"
  get 'order_lines/:id/reduce' => "order_lines#reduce_quantity", as: "orders_reduce"
  post 'order_lines/:id/reduce' => "order_lines#reduce_quantity", as: "order_lines_reduce"
  delete 'order_lines/:id' => "order_lines#destroy"

  # resources :order_lines do
  #   collection do
  #     get 'previous_order'
  #   end
  # end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!

  def cart
    @order = Order.find_or_create_by(user: current_user, status: :cart)
    @order_sorted = @order.order_lines.order(created_at: :desc)
    @order_sorted
  end
end

app/views/cart/cart.html.erb
<%= render "shared/top_nav" %>

<h1 id="your-cart">Your Cart</h1>
<% if @order.order_lines.empty? %>
  <p class="empty-cart text-center">Your cart is currently empty...</p>
  <p class="empty-text">You must add some products to your cart before checking out</p>
  <div class="cart">
    <%= image_tag "https://cdn-icons-png.flaticon.com/512/2038/2038854.png", alt: "empty-cart", class: "empty-cart-icon" %>
  </div>
<% else %>

  <% total_price = 0 %>
  <% @order_sorted.each do |ol| %>
  <div class="cart-item-container">
  <ul id="cart-food-infos">
    <li>
      <% if ol.food.photo.attached? %>
        <%= cl_image_tag(ol.food.photo.key, width:70, height:70, class: "cart-food", crop: :fill, gravity: :center) %>
      <% end %>
    </li>
    <li class="cart-text"><h6 style="color: #f3844c"><strong>Food Name: </h6></strong><h6 style="color: #789d67"><%= ol.food.name %></h6></li>
    <li class="cart-text"><h6 style="color: #f3844c">
      <strong>Quantity: </h6></strong>
      <%= link_to order_lines_reduce_path(:id => ol), class: "minus", method: :post do %>
        <i class="fa-solid fa-minus"></i>
      <% end %>
      <%= ol.quantity %> <%= link_to order_lines_add_path(:id => ol), class: "plus", method: :post do %>
        <i class="fa-solid fa-plus"></i>
      <% end %>
    </li>
    <li class="cart-text"><h6 style="color: #f3844c"><strong>Description: </h6></strong><%= ol.food.description %> </li>
      <div class="delete">
    <li class="cart-text"><h6 style="color: #f3844c"><strong>Price: </h6></strong><%= number_to_currency(ol.food.price * ol.quantity) %></li>
        <%= link_to order_lines_path(ol), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this item?"}, class: "delete-btn" do %>
          <i class="fa-solid fa-trash-can" style="color: #ff0000;"></i>
        <% end %>
      </div>
    <% number_to_currency(total_price +=  ol.food.price * ol.quantity) %>
  </ul>
  </div>
<% end %>

<div id="total">
  <h6 class="total">Total price:  </h6><h6 class="total" style="color: #f3844c"><%= number_to_currency(total_price) %></h6>
</div>

<div class="cart-wrap-button">
  <div class="proceed">
    <%= link_to "Proceed to checkout",  order_path(@order), class: "proceed-btn-positive" %>
    <% end %>
  </div>
  <div class="continue">

  <% if @order.restaurant %>
    <%= link_to "Continue shopping", restaurant_path(@order.restaurant), class: "continue-btn-positive" %>
  <% else %>
  <%= link_to "Continue shopping", restaurants_path, class: "continue-btn-positive" %>
  <% end %>
  </div>
</div>
<br><br>