config/routes.rb
Rails.application.routes.draw do
  get 'cart/cart'
  devise_for :restaurants, controllers: {
    registrations: 'restaurants/registrations',
    sessions: 'restaurants/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to: "pages#home"
  # root to: "pages#authentication"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "pages/auth", to: "pages#authentication", as: :auth
  # routes for pages
  resources :pages
  # Defined routes for the restaurants
  get 'restaurants/dashboard', to: 'restaurants/dashboard#dashboard'
  get 'restaurants/:id/notification', to: 'restaurants/dashboard#notification', as: :restaurant_notification
  get 'users/dashboard', to: 'users/dashboard#dashboard'
  get 'users/:id/notification', to: 'users/dashboard#notification', as: :user_notification

  resources :restaurants do
    resources :reviews
    # Nested routes - foods belonging to restaurant
    resources :foods, only: [:new, :create, :edit, :index, :show]
    resources :foods, only: [:new, :create, :index, :show] do
      member do
        patch :published, :unpublished
      end
    end

    # Nested routes - reviews belonging to restaurant
    resources :reviews, only: [:index, :create, :new]
    # Nested routes - orders related to a specific restaurant
    # resources :orders, only: [:index, :create, :new]
  end

  resources :foods do
    resources :order_lines, only: [:create]
    patch :published, on: :collection
  end

  resources :orders do
    member do
      patch 'checkout'
    end
    collection do
      get 'past'
    end
  end



  resources :foods, only: [:edit, :update, :destroy, :show]

  get '/search', to: 'search#list', as: :search
  get '/search/map', to: 'search#map', as: :search_map

  # routes related to orders and carts
  get '/cart', to: 'cart#cart', as: :cart
  get 'order_lines/:id' => "order_lines#show", as: "order_lines"

  get 'order_lines/:id/add' => "order_lines#add_quantity", as: "orders_lines_quantity"
  post 'order_lines/:id/add' => "order_lines#add_quantity", as: "order_lines_add"
  get 'order_lines/:id/reduce' => "order_lines#reduce_quantity", as: "orders_reduce"
  post 'order_lines/:id/reduce' => "order_lines#reduce_quantity", as: "order_lines_reduce"
  delete 'order_lines/:id' => "order_lines#destroy"

  # resources :order_lines do
  #   collection do
  #     get 'previous_order'
  #   end
  # end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div data-controller="alert" data-alert-target="flash" class="alert alert-info alert-dismissible fade show m-1 notice-btn" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div data-controller="alert" data-alert-target="flash" class="alert alert-warning alert-dismissible fade show m-1 alert-btn" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-bottom_spacer" style="height: 75px;">
</div>
<div class="navbar navbar-expand-sm bg-dark-subtle2 "  id="navbar-bottom">
  <div class="container mx-3">
    <div class="navbar" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mx-3">
        <% if user_signed_in? %>
        <ul class="nav nav-underline">
          <li class="nav-item position-relative">
            <%= link_to restaurants_path, class: "nav-link px-3" do %>
              <i class="fa-solid fa-house"></i>
            <% end %>
            <% if current_page?(restaurants_path) %>
              <div class="position-absolute bottom-0 w-100" style="background: #ff5e0eb5; height: 2px;"></div>
            <% end  %>
          </li>
          <li class="nav-item position-relative">
            <%= link_to user_notification_path(current_user), class: "nav-link px-3" do %>
              <i class="fa-solid fa-bell"></i>
            <% end %>
            <% if current_page?(user_notification_path(current_user)) %>
              <div class="position-absolute bottom-0 w-100" style="background: #ff5e0eb5; height: 2px;"></div>
            <% end  %>
          </li>
          <li class="nav-item position-relative">
            <%= link_to cart_path, class: "nav-link px-3" do %>
              <i class="fa-solid fa-cart-shopping"></i>
            <% end %>
            <% if current_page?(cart_path) %>
              <div class="position-absolute bottom-0 w-100" style="background: #ff5e0eb5; height: 2px;"></div>
            <% end  %>
          </li>
          <li class="nav-item position-relative">
            <%= link_to users_dashboard_path, class: "nav-link px-3" do %>
              <i class="fa-solid fa-user"></i>
            <% end %>
            <% if current_page?(users_dashboard_path) %>
              <div class="position-absolute bottom-0 w-100" style="background: #ff5e0eb5; height: 2px;"></div>
            <% end  %>
          </li>
        </ul>
        <% elsif restaurant_signed_in?%>
          <ul class="nav nav-underline">
            <li class="nav-item position-relative">
              <%= link_to restaurants_path, class: "nav-link px-3" do %>
                <i class="fa-solid fa-house"></i>
              <% end %>
              <% if current_page?(restaurants_path) %>
                <div class="position-absolute bottom-0 w-100" style="background: #ff5e0eb5; height: 2px;"></div>
              <% end  %>
            </li>
            <li class="nav-item position-relative">
              <%= link_to restaurant_notification_path(current_restaurant), class: "nav-link px-3" do %>
                <i class="fa-solid fa-bell"></i>
              <% end %>
              <% if current_page?(restaurant_notification_path(current_restaurant)) %>
                <div class="position-absolute bottom-0 w-100" style="background: #ff5e0eb5; height: 2px;"></div>
              <% end  %>
            </li>

            <li class="nav-item">
            <li class="nav-item position-relative">
              <%= link_to restaurants_dashboard_path, class: "nav-link px-3" do %>
                <i class="fa-solid fa-user"></i>
              <% end %>
              <% if current_page?(restaurants_dashboard_path) %>
                <div class="position-absolute bottom-0 w-100" style="background: #ff5e0eb5; height: 2px;"></div>
              <% end  %>
            </li>

            <li class="nav-item">
              <div class="dropup-center dropup">
                <button type="button" class="nav-link px-3 dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="fa-solid fa-bars"></i>
                </button>
                <ul class="dropdown-menu">
                  <%= link_to "Add New Food Item", new_restaurant_food_path(current_restaurant), class: "dropdown-item" %>
                  <%= link_to "Manage Your Menu", restaurant_foods_path(current_restaurant), class: "dropdown-item" %>
                  <%= link_to "Help Centre", "#", class: "dropdown-item" %>
                  <%= link_to "Notification", restaurant_notification_path(current_restaurant), class: "dropdown-item" %>
                  <%= link_to "Log Out", destroy_restaurant_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
                </ul>
              </div>
            </li>
          </ul>

        <% else %>
            <li class="nav-item">
              <%= link_to "Login", auth_path, class: "nav-link" %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<%#= link_to "Log out", destroy_restaurant_session_path, data: {turbo_method: :delete}, class: "btn btn-primary" %>

app/views/shared/_top_nav.html.erb
<div class="nav-top">
  <% unless current_page?(restaurants_path) %>
  <div class="back">
    <%= link_to 'javascript:history.back()' do %>
      <i class="fa-solid fa-angle-left"></i>
    <% end %>
  </div>
  <% end %>
  <%= image_tag "www-logo2.png", alt: "Logo", class: "logo-img" %>
</div>