config/routes.rb
Rails.application.routes.draw do
  get 'cart/cart'
  devise_for :restaurants, controllers: {
    registrations: 'restaurants/registrations',
    sessions: 'restaurants/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to: "pages#home"
  # root to: "pages#authentication"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "pages/auth", to: "pages#authentication", as: :auth
  # routes for pages
  resources :pages
  # Defined routes for the restaurants
  get 'restaurants/dashboard', to: 'restaurants/dashboard#dashboard'
  get 'restaurants/:id/notification', to: 'restaurants/dashboard#notification', as: :restaurant_notification
  get 'users/dashboard', to: 'users/dashboard#dashboard'
  get 'users/:id/notification', to: 'users/dashboard#notification', as: :user_notification

  resources :restaurants do
    resources :reviews
    # Nested routes - foods belonging to restaurant
    resources :foods, only: [:new, :create, :edit, :index, :show]
    resources :foods, only: [:new, :create, :index, :show] do
      member do
        patch :published, :unpublished
      end
    end

    # Nested routes - reviews belonging to restaurant
    resources :reviews, only: [:index, :create, :new]
    # Nested routes - orders related to a specific restaurant
    # resources :orders, only: [:index, :create, :new]
  end

  resources :foods do
    resources :order_lines, only: [:create]
    patch :published, on: :collection
  end

  resources :orders do
    member do
      patch 'checkout'
    end
    collection do
      get 'past'
    end
  end



  resources :foods, only: [:edit, :update, :destroy, :show]

  get '/search', to: 'search#list', as: :search
  get '/search/map', to: 'search#map', as: :search_map

  # routes related to orders and carts
  get '/cart', to: 'cart#cart', as: :cart
  get 'order_lines/:id' => "order_lines#show", as: "order_lines"

  get 'order_lines/:id/add' => "order_lines#add_quantity", as: "orders_lines_quantity"
  post 'order_lines/:id/add' => "order_lines#add_quantity", as: "order_lines_add"
  get 'order_lines/:id/reduce' => "order_lines#reduce_quantity", as: "orders_reduce"
  post 'order_lines/:id/reduce' => "order_lines#reduce_quantity", as: "order_lines_reduce"
  delete 'order_lines/:id' => "order_lines#destroy"

  # resources :order_lines do
  #   collection do
  #     get 'previous_order'
  #   end
  # end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :restaurant
  # belongs_to :user
  has_many :order_lines, dependent: :destroy
  has_one_attached :photo

  def self.published
    where(published: true)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    # @foods = Food.all
    if current_restaurant.present?
      @unpublished_foods = Food.where(published: false)
      @my_restaurant = current_restaurant
      @foods = @unpublished_foods
    elsif user_signed_in?
      @restaurant = Restaurant.find(params[:restaurant_id])
      @foods = @restaurant.foods.where(published: true)
    else
      redirect_to select_restaurant_path, notice: "You are not signed-in"
    end
  end

  # def index
  #   if current_restaurant.present?
  #     @my_restaurant = current_restaurant
  #     @foods = @my_restaurant.foods
  #     @unpublished_foods = @my_restaurant.foods.where(published: false)
  #   else

  #     redirect_to select_restaurant_path,
  #   end
  # end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @food = Food.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @food = Food.new(food_params)
    @food.restaurant = @restaurant
    @food.restaurant = @restaurant
    if @food.save
      redirect_to restaurant_foods_path, notice: "food created successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def published
    @restaurant = Restaurant.find(params[:restaurant_id])
    @food = Food.find(params[:id])
    @food.update(published: true)
    redirect_to foods_path
  end

  def unpublished
    @restaurant = Restaurant.find(params[:restaurant_id])
    @food = Food.find(params[:id])
    @food.update(published: false)
    redirect_to restaurants_dashboard_path
  end

  def show
    # @restaurant = Restaurant.find(params[:restaurant_id])
    @food = Food.find(params[:id])
  end

  def edit
    @food = Food.find(params[:id])
    @restaurant = @food.restaurant
  end

  # patch /foods/:id
  def update
    @food = Food.find(params[:id])
    @restaurant = @food.restaurant
    @food.update(food_params)
    # redirect_to restaurant_path(@restaurant)
    respond_to do |format|
      format.html { redirect_to restaurant_foods_path(@restaurant) }
      format.json { render json: @food.to_json }
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @restaurant = @food.restaurant
    @food.destroy
    # redirect_to restaurant_path(@restaurant), status: :see_other
    redirect_to restaurant_foods_path(@restaurant), status: :see_other
  end

  private

  def food_params
    params.require(:food).permit(:name, :price, :description, :allergen, :quantity, :restaurant_id, :user_id, :photo, :published, :bestseller)
  end
end

app/views/foods/edit.html.erb
<div class="nav-top">
<%# go-back-icon %>
<div class="back"><%= link_to 'javascript:history.back()' do %>
<i class="fa-solid fa-angle-left"></i>
<% end %></div>
<%= image_tag "www-logo.png", alt: "Logo", class: "logo-img" %>
<%#= button_tag "Search", type: :button, onclick: "window.location.href = '#'", class: "button-negative" %>
</div>

<h1 class="text-center mt-5">Edit <%= @food.name %>'s details</h1>

<div class="edit-form d-flex flex-column align-items-center">
  <%= simple_form_for @food, method: :patch do |f| %>
      <%= f.input :name %>
      <%= f.input :price %>
      <%= f.input :description %>
      <%= f.input :allergen %>
      <%= f.input :quantity %>
      <%= f.input :photo, as: :file %>
      <%= f.submit class:"btn btn-success update-food"%>
  <% end %>
  <p class="text-center">or</p>
    <%# delete btn %>
  <div class="btn">
    <%#= link_to food_path(@food), data: { turbo_method: :delete }, style: "text-decoration: none" do %>
    <%# <h3 class="btn btn-danger">Delete this item</h3> %>
    <%# end %>
    <%= link_to "Delete this item", food_path(@food), data: {turbo_method: :delete, turbo_confirm: "Do you really want to delete #{ERB::Util.html_escape(@food.name)}?"}, class: 'button-negative' %>
  </div>
</div>

app/views/foods/index.html.erb
<div class="nav-top">
<%# go-back-icon %>
<div class="back"><%= link_to 'javascript:history.back()' do %>
<i class="fa-solid fa-angle-left"></i>
<% end %></div>
<h1 class= "text-center mt-5">Restaurant's Menu</h1>
<%#= button_tag "Search", type: :button, onclick: "window.location.href = '#'", class: "button-negative" %>
</div>

<div class="mt-3">
  <h2 class="text-center">Unpublished menu items</h2>
  <% if restaurant_signed_in? %>
  <ul>
    <% @foods.each do |food| %>

    <div class="food-card d-flex p-2" style="width: 380px;">
      <%# <div class="card-food-index"> %>

        <% if food.photo.attached? %>
          <%= cl_image_tag food.photo.key, height: 200, width: 180, crop: :fill, class: "food-index" %>
        <% else %>
          <img style="width: 150px" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
        <% end %>

        <div class="d-flex flex-wrap ms-2">
          <li id="food-name"><%= food.name %> </li>
          <li id="food-description"><%= food.description %> </li>
          <li id="food-price">Quantity: <%= food.quantity %> </li>
        </div>

      <%# </div> %>
      <div class="d-flex flex-column justify-content-between align-items-center p-2">
        <li id="food-price"><%= number_to_currency(food.price) %> </li>
        <%# <div class="edit-icon"> %>
        <%= link_to edit_food_path(food) do %>
          <i class="fa-solid fa-pen-to-square" style="color: #F3844C;"></i>
        <% end %>
        <%# </div> %>
        <%= link_to published_restaurant_food_path(food.restaurant, food), data: { turbo_method: :patch } do %>
          <h4 class="btn-publish">Publish</h4>
        <% end %>
      </div>
    </div>

    <% end %>
  </ul>
</div>

<div class="publish">
  <%= link_to "See your published menu",  restaurants_dashboard_path(@restaurant), class: "publish-btn-positive" %>
</div>

<br>

<%# USER (CUSTOMER) LOG-IN %>
<% elsif user_signed_in? %>
  <ul>
    <% @foods.each do |food| %>
      <div class="food-card">
        <div class="card-product-infos">
          <% if food.photo.attached? %>
            <%= cl_image_tag food.photo.key, height: 180, width: 150, crop: :fill %>
          <% else %>
            <img style="width: 150px" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
          <% end %>
            <div class="text-infos">
              <li id="food-name"><%= food.name %> </li>
              <li id="food-price"><%= number_to_currency(food.price) %> </li>
              <li id="food-description"><%= food.description %> </li>
              <li>Restaurant : <strong><%= food.restaurant.name %></strong></li>
              <br>
              <div class="btn">
                <%= link_to "add to cart", food_order_lines_path(food), data: { turbo_method: :post } %><%# fix message%>
                <%#= link_to "add to cart", food_order_lines_path(food), data: { turbo_method: :post, turbo_confirm: "Are you sure you want to submit this form?" } %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <%# BUTTON: CONTINUE SHOPPING %>
    <div class="btn">
      <%= link_to 'Continue shopping', restaurants_path, class: 'btn-positive mt-3', data: {'turbo_confirm': "Are you sure you want to submit this form?" } %> <%# fix message%>
    </div>
  </ul>
<% end %>

app/views/foods/new.html.erb
<%# food form %>
<div class="nav-top">
<%# go-back-icon %>
<div class="back"><%= link_to 'javascript:history.back()' do %>
<i class="fa-solid fa-angle-left"></i>
<% end %></div>
<%= image_tag "www-logo.png", alt: "Logo", class: "logo-img" %>
<%#= button_tag "Search", type: :button, onclick: "window.location.href = '#'", class: "button-negative" %>
</div>

<div class="d-flex justify-content-center">
  <div class="form-wrap m-5" style="width: 35rem;">
  <br>
  <h2 class="text-center dashboard-heading">Add food item to <%= @restaurant.name %>'s' menu</h2>

  <div class="form m-5 ml-5">
    <%= simple_form_for [@restaurant, @food] do |f| %>
      <%= f.input :name, placeholder: "Food Name"%>
      <%= f.input :price, placeholder: "Price" %>
      <%= f.input :description, placeholder: "Description" %>
      <%= f.input :allergen, placeholder: "allergen"%>
      <%= f.input :quantity, placeholder: "Quantity" %>
      <%= f.input :photo, as: :file %>
      <%= f.submit class:"btn btn-success"%>
    <% end %>
  </div>
</div>
</div>
<%# button %>
<div class="button-container">
  <div class="btn d-flex justify-content-center">
  <span ><%= link_to "Back to Home", root_path, class: "btn-home" %></span>
    </div>
</div>
<br><br>

app/views/foods/show.html.erb
<div class="nav-top">
<%# go-back-icon %>
<div class="back"><%= link_to 'javascript:history.back()' do %>
<i class="fa-solid fa-angle-left"></i>
<% end %></div>
<%= image_tag "www-logo.png", alt: "Logo", class: "logo-img" %>
<%#= button_tag "Search", type: :button, onclick: "window.location.href = '#'", class: "button-negative" %>
</div>
<%# food item photo %>
<div class="container food-show-page">
<h2 class="text-center"> <%= @food.name %> details </h2>

  <% if @food.photo.attached? %>
    <%= cl_image_tag @food.photo.key, height: 200, width: 200, crop: :fill %>
  <% else %>
    <img style="width: 150px" src="https://hips.hearstapps.com/hmg-prod/images/delish-200511-seo-club-sandwich-h-14383-eb-1590780714.jpg?crop=0.671xw:1.00xh;0.123xw,0&resize=1200:*" />
  <% end %>

  <div class="detail-box d-flex justify-content-center">
  <ul>
      <li>Name: <%= @food.name %></li>
      <li>Price: <%= number_to_currency(@food.price) %></li>
      <li>Description: <%= @food.description %></li>
      <li id="allergen">Allergen: <p style="color: #f3844c;"><%= @food.allergen%></p></li>
       <div><li id="qty-left" style="color: black;"><p style="color: #FF9800;"><%= @food.quantity %></p> left</li></div>
  </ul>

  </div>
  <div class="add-cart-btn" >
  <% if user_signed_in? %>
    <%= link_to "Add to cart", food_order_lines_path(@food), data: { turbo_method: :post }, class: "add-cart-btn-show" %>
  <% end %>
</div>
</div>