config/routes.rb
Rails.application.routes.draw do
  get 'cart/cart'
  devise_for :restaurants, controllers: {
    registrations: 'restaurants/registrations',
    sessions: 'restaurants/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to: "pages#home"
  # root to: "pages#authentication"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "pages/auth", to: "pages#authentication", as: :auth
  # routes for pages
  resources :pages
  # Defined routes for the restaurants
  get 'restaurants/dashboard', to: 'restaurants/dashboard#dashboard'
  get 'restaurants/:id/notification', to: 'restaurants/dashboard#notification', as: :restaurant_notification
  get 'users/dashboard', to: 'users/dashboard#dashboard'
  get 'users/:id/notification', to: 'users/dashboard#notification', as: :user_notification

  resources :restaurants do
    resources :reviews
    # Nested routes - foods belonging to restaurant
    resources :foods, only: [:new, :create, :edit, :index, :show]
    resources :foods, only: [:new, :create, :index, :show] do
      member do
        patch :published, :unpublished
      end
    end

    # Nested routes - reviews belonging to restaurant
    resources :reviews, only: [:index, :create, :new]
    # Nested routes - orders related to a specific restaurant
    # resources :orders, only: [:index, :create, :new]
  end

  resources :foods do
    resources :order_lines, only: [:create]
    patch :published, on: :collection
  end

  resources :orders do
    member do
      patch 'checkout'
    end
    collection do
      get 'past'
    end
  end



  resources :foods, only: [:edit, :update, :destroy, :show]

  get '/search', to: 'search#list', as: :search
  get '/search/map', to: 'search#map', as: :search_map

  # routes related to orders and carts
  get '/cart', to: 'cart#cart', as: :cart
  get 'order_lines/:id' => "order_lines#show", as: "order_lines"

  get 'order_lines/:id/add' => "order_lines#add_quantity", as: "orders_lines_quantity"
  post 'order_lines/:id/add' => "order_lines#add_quantity", as: "order_lines_add"
  get 'order_lines/:id/reduce' => "order_lines#reduce_quantity", as: "orders_reduce"
  post 'order_lines/:id/reduce' => "order_lines#reduce_quantity", as: "order_lines_reduce"
  delete 'order_lines/:id' => "order_lines#destroy"

  # resources :order_lines do
  #   collection do
  #     get 'previous_order'
  #   end
  # end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_many :foods, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :notifications, dependent: :destroy
  # has_many :orders, dependent: :destroy

  has_one_attached :photo

  geocoded_by :address

  after_validation :geocode, if: :will_save_change_to_address?

  geocoded_by :address do |obj, results|
    if geo = results.first
      obj.latitude = geo.latitude
      obj.longitude = geo.longitude
    end
  end
end

app/controllers/restaurants/dashboard_controller.rb
class Restaurants::DashboardController < ApplicationController
  def dashboard
    @restaurant = Restaurant.find(current_restaurant.id)
    @unpublished_foods = @restaurant.foods.where(published: false)
    @published_foods = @restaurant.foods.where(published: true)
  end

  def notification
    @restaurant = Restaurant.find(current_restaurant.id)
  end
end

app/controllers/restaurants/registrations_controller.rb
class Restaurants::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?
  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_no, :name, :cuisine, :phone_no, :rating, :email, :address, :pickup_start, :pickup_end, :photo ])
  end
end

app/controllers/restaurants/sessions_controller.rb
class Restaurants::SessionsController < Devise::SessionsController
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
    @published_foods = Food.published

    # Signed-in restaurant only
    if restaurant_signed_in?
      @my_restaurant = current_restaurant
      @published_foods = @my_restaurant.foods.where(published: true)
      # fetch all other restaurants (excluding signed-in restaurant)
      @other_restaurants = Restaurant.where.not(id: @my_restaurant&.id)
    else
      # fetches all restaurants
      @my_restaurant = nil
      @other_restaurants = Restaurant.all
    end
    # Grab all foods from signed-in restaurant
    @foods = Food.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @my_restaurant = current_restaurant if restaurant_signed_in?
    # @food = Food.find(params[:id])
    @published_foods = @restaurant.foods.where(published: true)
    @unpublished_foods = @restaurant.foods.where(published: false)

    # if restaurant_signed_in?
    #   @my_restaurant = current_restaurant

    # end
  end

  # def map
  #   @restaurants = Restaurant.all
  #   @markers = @restaurants.geocoded.map do |restaurant|
  #     {
  #       lat: restaurant.latitude,
  #       lng: restaurant.longitude
  #     }
  #   end
  # end

  # def create
  #   @restaurant = Restaurant.new(restaurant_params)
  #   @restaurant.user = current_user
  #   if @restaurant.save
  #     redirect_to restaurants_path_, notice: "Restaurant created successfully"
  #   else
  #     render :new, status: :unprocessable_entity
  #   end
  # end

  # def edit
  #   @restaurant = Restaurant.find(params[:id])
  # end

  # def new
  #   @restaurant = Restaurant.new
  #   @restaurant.save
  # end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  # def destroy
  #   @restaurant = Restaurant.find(params[:id])
  #   @restaurant.destroy
  #   redirect_to restaurants_path, status: :see_other
  # end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :cuisine, :address, :phone_no, :email, :rating, :pickup_start, :pickup_end, :latitude, :longitude, :published )
  end
end

app/views/restaurants/_map.html.erb
<div id="map" class="mt-3">
  <div style="width: 100%; height: 735px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/restaurants/_restaurant_card.html.erb
<%# EACH CARD OF RESTUARANT %>
<%#= link_to '🡰', 'javascript:history.back()' %>
    <%= link_to restaurants_dashboard_path(restaurant) do %>
      <div class="card card-product restaurants-main-card">
        <div class="card-img">
          <h5 class="card-img-name"><%= restaurant.name %></h5>
          <% if restaurant.photo.attached? %>
            <%= cl_image_tag(restaurant.photo.key, class: "object-fit-cover-my-restaurant", crop: :fill, gravity: :face) %>
          <% else %>
            <p>No images available for <%= restaurant.name %></p>
          <% end %>
        </div>
        <%# float restaurant name and location onto image %>
        <%# <div class="mask d-flex justify-content-center align-items-center flex-column text-center rounded px-2 "> %>
          <%# <h5 class="card-img-overlay text-center"><%= restaurant.name</h5>  %>
          <%# <p class="card-img-overlay text-center"><%= restaurant.address</p>  %>
        <%# </div> %>

        <div class="overlay d-flex justify-content-center align-items-center flex-column text-center px-2">
          <div class="card-text-container">
            <p class="card-img-overlay text-center d-flex"><%#= restaurant.address %></p>
          </div>
        </div>
        <%# cuisine, rating, distance bottom of card image %>
        <div class="restaurant-card-info">
        <div class="cuisine">
          <p class="cuisine"><img id="food-icon" src="https://cdn-icons-png.flaticon.com/512/433/433087.png" alt="food-icon">  <%= restaurant.cuisine %></p>
        </div>
          <p class="text-center"><% restaurant.rating.to_i.times do %></p>
              <i class="fa-solid fa-star" style="color: #FFD43B; margin: 0px;"></i>
          <% end %>
        
        </div>

      </div>
    <% end %>

app/views/restaurants/edit.html.erb
<h1>Edit</h1>

app/views/restaurants/index.html.erb
<%# SIGNED IN AS RESTAURANT %>
<%= render "shared/top_nav" %>
<div class="container">
  <%= link_to (search_map_path) do %>
    <div class="view-map">View map  <i class="fa-solid fa-map"></i></div>
  <% end  %>
</div>
<%# -------------------------------------------------------------- %>
<%# RESTAURANT SIGN-IN %>
<% if restaurant_signed_in? %>
  <%# PUBLISHED FOODS FOR @MY_RESTAURANT %>
  <h3 class="index-head">My Published Menu</h3>
  <% if @current_restaurant.foods.published.empty? %>
  <p class="if-menu-empty">No food items that are published at the moment ...</p>
  <div id="menu-empty">
  <%= image_tag "https://cdn-icons-png.flaticon.com/512/151/151409.png", alt: "empty-menu", class: "empty-menu-icon" %>
  </div>
  <% else %>
  <div class="carousel" data-flickity='{ "wrapAround": true }'>
    <% @current_restaurant.foods.published.each do |food| %>
      <div class="carousel-cell">
        <div class="card restaurant-foodlist">
          <div class="card-img-top">
            <% if food.photo.attached? %>
              <%= cl_image_tag(food.photo.key, width:200, height:200, class: "object-fit-cover", crop: :fill, gravity: :center) %>
            <% else %>
              <img class="restaurant-photo" src="https://img.delicious.com.au/MYhAwMVF/del/2023/01/sandoitchi-181514-1.jpg" alt="cafe-photo">
            <% end %>
            <div class="card-text">
              <p class="text-top"><%= food.name %></p>
              <p class="text">  <%= number_to_currency(food.price) %></p>
              <p class="text">qty:  <%= food.quantity %></p>
              <p class="text-description"><%= food.description %></p>
            </div>
          </div>
          <%# float food name onto image %>
        </div>
  </div>
  <% end %>
</div>
    <% end %>
<%# ------------------------------------------------------------ %>
  <%# CARDS OF RESTAURANTS %>
  <%# SIGNED-IN RESTAURANT ONLY %>
  <h3 id="my-restaurant">My Restaurant</h3>
    <div class="container mx-auto container-signedin-restaurant">
      <div class="card signedin-restaurant">
        <% if @my_restaurant.present? %>
          <%= render 'restaurant_card', restaurant: @my_restaurant %>
        <% else %>
          <p>No signed-in restaurant found.</p>
        <% end %>
      </div>
    </div>
<%# ------------------------------------------------------------- %>
  <%# LIST OF OTHER RESTAURANTS %>
  <h3 class="index-head">List of available Restaurants</h3>
  <div class="available-restaurant">
    <% @other_restaurants.each do |restaurant| %>
      <%# EACH CARD OF RESTUARANT %>
      <%= link_to restaurant_path(restaurant) do %>
        <div class="card card-product restaurants-second-card">
          <div class="card-img">
            <h5 class="card-img-name "><%= restaurant.name %></h5>
            <% if restaurant.photo.attached? %>
              <%= cl_image_tag(restaurant.photo.key, width:200, height:170, class: "cover-my-restaurant-owner", crop: :fill, gravity: :face) %>
            <% else %>
              <%# <p>No images available for <%= restaurant.name %></p>
              <img class="restaurant-photo" src="https://img.delicious.com.au/MYhAwMVF/del/2023/01/sandoitchi-181514-1.jpg" alt="cafe-photo">
            <% end %>
          </div>
          <%# float restaurant name and location onto image %>
          <div class="mask">
            <p class="text-center">Address: <%= restaurant.address %></p>
          <%# cuisine, rating, distance bottom of card image %>
          <h5 class="text-center">Cuisine: <%= restaurant.cuisine %></h5>
          <div class="rating d-flex">
          <p class="text-center"><% restaurant.rating.to_i.times do %></p>
              <i class="fa-solid fa-star" style="color: #FFD43B; margin: 0px;"></i>
          <% end %>
          </div>
          </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <br><br><br>

<%# ------------------------------------------------------------- %>
<% elsif user_signed_in? %>

<%# SIGNED IN AS USER %>

<%# RESTAURANTS CARDS - random display %>
<div id="welcome-aboard"><p style="color: #f3844c">Hey <%=current_user.first_name.capitalize %>!</p><p id="hello"> Welcome aboard <i class="fa-solid fa-utensils"></i></p></div>
<h3 class="index-head">My Favourite Restaurants</h3>
<!-- Flickity HTML init -->
<div class="carousel"
  data-flickity='{ "wrapAround": true }'>
  <% @restaurants.shuffle.each do |restaurant| %>
      <div class="carousel-cell">
    <div class="card restaurants-list">
      <div class="card-img-top-user">
        <% if restaurant.photo.attached? %>
          <%= cl_image_tag(restaurant.photo.key, width:240, height:200, class: "object-fit-cover", crop: :fill, gravity: :face) %>
        <% else %>
          <img class="restaurant-user-photo" src="https://img.delicious.com.au/MYhAwMVF/del/2023/01/sandoitchi-181514-1.jpg" alt="cafe-photo">
              <%# <p>No images available for <%= restaurant.name %>
        <% end %>
        <div class="card-text">
          <p class="text-top"><%= restaurant.name %></p>
          <p class="text"><%= restaurant.cuisine %></p>
          <p class="text"><%= restaurant.address %></p>
        </div>
          </div>
          <%# float food name onto image %>
        </div>
  </div>
  <% end %>
</div>

  <%# LIST OF ALL RESTAURANTS %>
  <h4 class="index-list">List of available Restaurants</h4>
  <div class="container mx-auto card-container-restaurants">
    <% @other_restaurants.each do |restaurant| %>
      <%# EACH CARD OF RESTUARANT %>
      <%= link_to restaurant_path(restaurant) do %>
        <div class="card card-product restaurants-main-card-user">
          <div class="card-img">
            <% if restaurant.photo.attached? %>
              <%= cl_image_tag(restaurant.photo.key, class: "cover-restaurant-user", crop: :fill, gravity: :face) %>
            <% else %>
              <%# <p>No images available for <%= restaurant.name %></p>
              <img class="restaurant-photo" src="https://img.delicious.com.au/MYhAwMVF/del/2023/01/sandoitchi-181514-1.jpg" alt="cafe-photo">
            <% end %>
          </div>
          <%# float restaurant name and location onto image %>
          <div class="card-infos-user">
          <p class="user-restaurant-name"><strong><%= restaurant.name %></strong></p>
          <p class="user-restaurant-cuisine"><%= restaurant.cuisine %></p>
          <% if restaurant.pickup_start && restaurant.pickup_end %>
           <div class="pick-up"> <p class="user-restaurant-pickup"><p id="pickup-time" style="color: black;">Pickup time: </p><p style="color: #f3844c;"><%= restaurant.pickup_start.strftime(" %I:%M%p")%></p> <p id="to">to</p> <p style="color: #f3844c;"><%= restaurant.pickup_end.strftime(" %I:%M%p")  %></p></div>
          <% end  %>
          </div>
          <%# cuisine, rating, distance bottom of card image %>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/restaurants/show.html.erb
<%= render "shared/top_nav" %>

<%# RESTAURANT OWNER SIGNED IN %>
<% if restaurant_signed_in? %>
  <% if current_restaurant == @restaurant %>
    <h2 class="text-center">Food Items to be Published</h2>
    <br>
    <% if @published_foods.empty? %>
      <p class="text-center">Your menu is currently empty.</p>
      <p class="text-center">Please use "add more food item" button below to add menus for your restaurant</p>
    <% else %>
      <% @published_foods.each do |food| %>
        <div class="food-card">
          <%# add to cart link %>
          <%= link_to food_order_lines_path(food), data: { turbo_method: :post } do %>
            <%= image_tag "https://www.svgrepo.com/show/2087/plus.svg", width: 20%>
          <% end %>
          <div class="card-product-infos">
            <% if food.photo.attached? %>
              <%= cl_image_tag food.photo.key, height: 80, width: 80, crop: :fill %>
            <% else %>
              <img style="width: 150px" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
            <% end %>
            <div class="text-infos-restaurants">
              <li id="food-name"><%= food.name %> </li>
              <li id="food-price"><%= number_to_currency(food.price) %> </li>
              <li id="food-description"><%= food.description %> </li>
              <%# edit icon %>
              <%= link_to edit_food_path(food) do %>
                <%= image_tag "https://w7.pngwing.com/pngs/944/137/png-transparent-pen-computer-icons-pen-angle-pencil-black-thumbnail.png", width: 20 %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>

    <br>
    <div class="btn">
      <%#= link_to 'Add more food item', restaurant_foods_path(@restaurant), class: 'btn-positive' %>
      <%= link_to 'Publish', restaurants_path, class: 'btn-positive mt-3' , method: :patch, data: { turbo_confirm: 'Are you sure?' }%>
    </div>
    <br>
  <% else %>
    <% if @published_foods.empty? %>
      <p class="text-center">Currently there is no menu available</p>
    <% else %>
      <% @published_foods.each do |food| %>
        <div class="food-card">
          <div class="card-product-infos">
            <% if food.photo.attached? %>
              <%= cl_image_tag food.photo.key, height: 80, width: 80, crop: :fill %>
            <% else %>
              <img  style="width: 150px" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
            <% end %>
            <div class="text-infos">
              <li id="food-name"><%= food.name %> </li>
              <li id="food-price">Price:<%= number_to_currency(food.price) %> </li>
              <li id="food-description">Quantity: <%= food.quantity %> </li>
              <li id="food-description">Description: <%= food.description%> </li>
                <%= link_to "Add to cart", food_order_lines_path(food), data: { turbo_method: :post }, class: "add-cart-btn" %>

                <%= link_to "Details", food_path(food) %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
<%# user log-in %>
<% elsif user_signed_in? %>
  <% if @published_foods.empty? %>
    <p class="text-center"><%= @restaurant.name %>'s menu is currently empty.</p>
    <p class="text-center">Please try a different restaurant by returning to the homepage</p>
  <% else %>
    <h3 class="choose-items"> Choose any food item below</h3>
    <% @published_foods.each do |food| %>
      <div class="food-card-user">
        <%# best seller IF ELSE STATEMENT %>
          <div class="show-bestseller">
            <% if food.bestseller? %>
            <div id="best-seller">
              best seller
              <i class="fa-solid fa-crown"></i>
            </div>
            <% end %>
          </div>
          <% if food.photo.attached? %>
            <%= cl_image_tag food.photo.key, height: 140, width: 140, crop: :fill, class: "food-img" %>
          <% else %>
            <img style="width: 150px" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
          <% end %>
          <div class="w-100">
            <div class="text-infos">
              <li id="food-name"><%= food.name %> </li>
              <li id="food-price"><%= number_to_currency(food.price) %> </li>
              <li id="food-description"><%= food.description %> </li>
              <div><li id="food-quantity2" style="color: black;"><p style="color: #FF9800;"><%= food.quantity %></p> left</li></div>
            </div>
            <div class="d-flex justify-content-end">
              <%= link_to "Details", food_path(food), class: "add-cart-btn" %>
              <%= link_to "Add to cart", food_order_lines_path(food), data: { turbo_method: :post }, class: "add-cart-btn" %>
            </div>
          </div>
        </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

<h3 class="details text-center"><%= @restaurant.name %>'s details</h3>
<div class="restaurant-info-card">
  <ul>
      <li class="d-flex justify-content-start align-items-baseline"><div class="details">Restaurant name:</div> <%= @restaurant.name %> </li>
      <% if @restaurant.pickup_start && @restaurant.pickup_start %>
        <li class="d-flex justify-content-start align-items-baseline"><div class="details">Pickup time:</div><%= @restaurant.pickup_start.strftime(" %I:%M%p")%> to <%= @restaurant.pickup_end.strftime(" %I:%M%p")  %></li>
      <% end  %>
      <li class="d-flex justify-content-start align-items-baseline"><div class="details">Cuisine : </div> <%= @restaurant.cuisine %> </li>
      <li class="d-flex justify-content-start align-items-baseline"><div class="details">Phone no : </div><%= @restaurant.phone_no %> </li>
      <li class="d-flex justify-content-start align-items-baseline"><div class="details">Address :</div> <%= @restaurant.address %> </li>
      <%# <div class="d-flex"> %>
        <li class="d-flex justify-content-start align-items-baseline"><div class="details">Rating:</div> <% @restaurant.rating.to_i.times do %>
        <i class="fa-regular fa-star fa-xs" style="color: #ffba24;"></i>
        <% end %>
      </li>
    </div>
  </ul>
</div>


<h3 class="reviews text-center">All reviews for <%= @restaurant.name %>:</h3>
  <div class="show-review-card">
    <% if @restaurant.reviews.empty? %>
      <p class="text-center">No reviews available</p>
    <% else %>
      <ul>
      <div class="content">
        <% @restaurant.reviews.each do |review| %>
          <li id="review-content">" <%= review.content %> "</li>
          <li>From: <%= review.user.first_name%> <%= review.user.last_name%></li>
          <hr>
        <% end %>
        </div>
      </ul>
    <% end %>
  </div>
<br>